export { default as Home } from './home/Home'
export { default as Contact } from './contact/Contact'
export { default as Login } from './auth/Login'
export { default as Signup } from './auth/Signup'
export { default as Reset } from './auth/Reset'
export { default as Admin } from './admin/Admin'
export { default as Cart } from './cart/Cart'
export { default as CheckoutDetails } from './checkout/CheckoutDetails'
export { default as Checkout} from './checkout/Checkout'
export { default as CheckoutSuccess} from './checkout/CheckoutSuccess'
export { default as OrderHistory} from './orderHistory/OrderHistory'
export { default as OrderDetails} from '../pages/orderDetails/OrderDetails'
export { default as Error404} from '../pages/error404/Error404'